# Preliminary Analysis for the Regression Project
## Josh Morgan Will Espanoza
We are starting with a basic analysis of the hubei data

In [1]:
import os.path as osp
import os
import pandas as pd
import numpy as np

In [7]:
path = os.getcwd()
data_path = osp.abspath(osp.join(path,'Data'))
hubei_path = osp.join(data_path,'ncov_hubei.csv')
hubei_df = pd.read_csv(hubei_path)
hubei_df.head()

,ID,age,sex,city,province,country,wuhan(0)_not_wuhan(1),latitude,longitude,geo_resolution,...,outcome,date_death_or_discharge,notes_for_discussion,location,admin3,admin2,admin1,country_new,admin_id,Unnamed: 32
0,1.0,15-88,male,Wuhan City,Hubei,China,0.0,30.62506,114.3421,admin2,...,NaN,NaN,NaN,NaN,NaN,Wuhan City,Hubei,China,420100.0,NaN
1,2.0,15-88,male,Wuhan City,Hubei,China,0.0,30.62506,114.3421,admin2,...,NaN,NaN,NaN,NaN,NaN,Wuhan City,Hubei,China,420100.0,NaN
2,3.0,15-88,male,Wuhan City,Hubei,China,0.0,30.62506,114.3421,admin2,...,NaN,NaN,NaN,NaN,NaN,Wuhan City,Hubei,China,420100.0,NaN
3,4.0,15-88,male,Wuhan City,Hubei,China,0.0,30.62506,114.3421,admin2,...,NaN,NaN,NaN,NaN,NaN,Wuhan City,Hubei,China,420100.0,NaN
4,5.0,15-88,male,Wuhan City,Hubei,China,0.0,30.62506,114.3421,admin2,...,NaN,NaN,NaN,NaN,NaN,Wuhan City,Hubei,China,420100.0,NaN

In [8]:
hubei_df.columns

Index(['ID', 'age', 'sex', 'city', 'province', 'country',
       'wuhan(0)_not_wuhan(1)', 'latitude', 'longitude', 'geo_resolution',
       'date_onset_symptoms', 'date_admission_hospital', 'date_confirmation',
       'symptoms', 'lives_in_Wuhan', 'travel_history_dates',
       'travel_history_location', 'reported_market_exposure',
       'additional_information', 'chronic_disease_binary', 'chronic_disease',
       'source', 'sequence_available', 'outcome', 'date_death_or_discharge',
       'notes_for_discussion', 'location', 'admin3', 'admin2', 'admin1',
       'country_new', 'admin_id', 'Unnamed: 32'],
      dtype='object')

#